#! /bin/bash

ARTIFACT=`pwd`/xx
MPICXX=mpic++
MPICC=mpicc

cmake \
    -D CMAKE_INSTALL_PREFIX:PATH="${ARTIFACT}" \
    -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
    -D CMAKE_INSTALL_RPATH:STRING="${ARTIFACT}/lib" \
    -D CMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON \
    -D CMAKE_BUILD_TYPE:STRING=Debug \
    -D CMAKE_PREFIX_PATH="${HASHSTACK}" \
    -D CMAKE_CXX_COMPILER:FILEPATH=${MPICXX} \
    -D CMAKE_C_COMPILER:FILEPATH=${MPICC} \
    -D Trilinos_INSTALL_INCLUDE_DIR:PATH=include/trilinos \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_PyTrilinos:BOOL=ON \
    -D Trilinos_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    -D BUILD_SHARED_LIBS:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_ENABLE_UMFPACK:BOOL=ON \
    -D BLAS_LIBRARY_NAMES:STRING=openblas \
    -D BLAS_LIBRARY_DIRS:PATH=${HASHSTACK}/lib \
    -D LAPACK_LIBRARY_NAMES:STRING=openblas \
    -D LAPACK_LIBRARY_DIRS:PATH=${HASHSTACK}/lib \
    -D UMFPACK_INCLUDE_DIRS:PATH=${HASHSTACK}/include/suitesparse \
    -D UMFPACK_LIBRARY_DIRS:PATH=${HASHSTACK}/lib \
    -D UMFPACK_LIBRARY_NAMES:STRING="umfpack;cholmod;camd;ccolamd;colamd;amd;suitesparseconfig" \
    -D SWIG_EXECUTABLE:FILEPATH=`which swig` \
    -D Trilinos_ENABLE_DEVELOPMENT_MODE:BOOL=OFF \
    -D PYTHON_EXECUTABLE:FILEPATH=`which python` \
    -D Teuchos_ENABLE_DEBUG:BOOL=ON \
    -D Teuchos_ENABLE_TESTS:BOOL=ON \
    ..

